version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        ports:
            - "3000:3000"
        
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=simple_blog_api
            - PGPASSWORD=postgres_password
            - POSTGRES_PORT=5432